echo "=== 设备基本信息 ==="
echo "作者:itnproject"
echo ""
echo "型号: $(getprop ro.product.model)"
echo "品牌: $(getprop ro.product.brand)"
echo "Android: $(getprop ro.build.version.release)"
echo "API: $(getprop ro.build.version.sdk)"
echo "CPU架构: $(getprop ro.product.cpu.abi)"
echo ""
echo "内核: $(uname -a)"
echo ""
echo "=== 内存信息 ==="
grep -E "MemTotal|MemFree|MemAvailable" /proc/meminfo
echo ""
echo "=== 存储信息 ==="
df -h
echo ""
echo "=== 电池 ==="
dumpsys battery | grep -E "level|status|health"